"""
LLM-Powered Analytics Engine for A3 Learning System.

This module aggregates behavioral data from various sources and uses an LLM
to generate personalized, actionable insights for students.

Key Features:
- Behavioral pattern analysis (study time patterns, learning velocity)
- Predictive analytics (completion forecast, at-risk detection)
- Personalized recommendations
- Anomaly detection (sudden drop-offs, unusual patterns)
"""

import json
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, asdict

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from core.logging import get_logger
from core.llm_client import llm_client
from models.database import (
    GeneratedQuiz,
    LearningEvent,
    LearningPath,
    QuizAttempt,
    StudentProfile,
    ChatSession,
    GeneratedResource,
    AnalyticsInsightsCache,
)

# Cache duration - insights are regenerated after this period
INSIGHTS_CACHE_DURATION_HOURS = 24  # Regenerate once per day

logger = get_logger(__name__)


@dataclass
class BehavioralData:
    """Aggregated behavioral data for a student."""
    student_id: str
    
    # Study patterns
    study_sessions: List[Dict[str, Any]]  # [{date, start_time, duration, topic}]
    preferred_study_hours: List[int]  # Hours of day (0-23)
    study_days_pattern: Dict[str, int]  # {Mon: 3, Tue: 1, ...}
    avg_session_duration: float  # minutes
    
    # Quiz performance
    quiz_attempts: List[Dict[str, Any]]  # [{topic, score, time_taken, weak_topics}]
    avg_quiz_score: float
    score_trend: str  # "improving", "declining", "stable"
    weak_topics: List[str]
    strong_topics: List[str]
    
    # Resource engagement
    resources_by_type: Dict[str, int]  # {notes: 5, video: 3, code: 2}
    total_resources_consumed: int
    preferred_resource_type: str
    
    # Tutor interactions
    tutor_sessions_count: int
    avg_messages_per_session: float
    common_question_topics: List[str]
    
    # Progress metrics
    path_completion_pct: float
    current_streak: int
    longest_streak: int
    days_since_last_activity: int
    
    # Velocity
    nodes_completed_last_7_days: int
    nodes_completed_last_30_days: int
    estimated_completion_days: Optional[int]


@dataclass
class LLMInsight:
    """Structured insight generated by the LLM."""
    category: str  # "pattern", "prediction", "recommendation", "alert"
    emoji: str
    title: str
    description: str
    confidence: float  # 0.0-1.0
    actionable: bool
    action_text: Optional[str] = None
    priority: str = "medium"  # "high", "medium", "low"


@dataclass
class AnalyticsReport:
    """Complete analytics report with LLM insights."""
    student_id: str
    generated_at: str
    behavioral_summary: Dict[str, Any]
    insights: List[Dict[str, Any]]
    predictions: Dict[str, Any]
    recommendations: List[Dict[str, Any]]
    alerts: List[Dict[str, Any]]


class AnalyticsEngine:
    """LLM-powered analytics engine for generating student insights."""
    
    def __init__(self):
        self.llm = llm_client
    
    async def get_insights(
        self,
        student_id: str,
        db: AsyncSession,
        force_refresh: bool = False,
    ) -> Dict[str, Any]:
        """
        Get insights for a student, using cache if available.
        
        Args:
            student_id: The student's ID
            db: Database session
            force_refresh: If True, regenerate even if cache is valid
            
        Returns:
            Dict with insights data and cache metadata
        """
        now = datetime.now(timezone.utc)
        
        # Check for cached insights
        if not force_refresh:
            cache_result = await db.execute(
                select(AnalyticsInsightsCache).where(
                    AnalyticsInsightsCache.student_id == student_id
                )
            )
            cached = cache_result.scalar_one_or_none()
            
            if cached and cached.expires_at > now:
                logger.info(f"Using cached insights for student: {student_id}")
                return {
                    "student_id": student_id,
                    "generated_at": cached.generated_at.isoformat(),
                    "expires_at": cached.expires_at.isoformat(),
                    "from_cache": True,
                    "generation_count": cached.generation_count,
                    **cached.insights_data,
                }
        
        # Generate fresh insights
        logger.info(f"Generating fresh LLM insights for student: {student_id}")
        report = await self._generate_fresh_insights(student_id, db)
        
        # Cache the results
        await self._cache_insights(student_id, report, db)
        
        return {
            "student_id": report.student_id,
            "generated_at": report.generated_at,
            "expires_at": (now + timedelta(hours=INSIGHTS_CACHE_DURATION_HOURS)).isoformat(),
            "from_cache": False,
            "generation_count": 1,
            "behavioral_summary": report.behavioral_summary,
            "insights": report.insights,
            "predictions": report.predictions,
            "recommendations": report.recommendations,
            "alerts": report.alerts,
        }
    
    async def _cache_insights(
        self,
        student_id: str,
        report: "AnalyticsReport",
        db: AsyncSession,
    ) -> None:
        """Cache the generated insights."""
        now = datetime.now(timezone.utc)
        expires_at = now + timedelta(hours=INSIGHTS_CACHE_DURATION_HOURS)
        
        # Check if cache entry exists
        cache_result = await db.execute(
            select(AnalyticsInsightsCache).where(
                AnalyticsInsightsCache.student_id == student_id
            )
        )
        existing = cache_result.scalar_one_or_none()
        
        insights_data = {
            "behavioral_summary": report.behavioral_summary,
            "insights": report.insights,
            "predictions": report.predictions,
            "recommendations": report.recommendations,
            "alerts": report.alerts,
        }
        
        if existing:
            # Update existing cache
            existing.insights_data = insights_data
            existing.behavioral_summary = report.behavioral_summary
            existing.generated_at = now
            existing.expires_at = expires_at
            existing.generation_count = (existing.generation_count or 0) + 1
            logger.info(f"Updated insights cache for student: {student_id} (gen #{existing.generation_count})")
        else:
            # Create new cache entry
            cache_entry = AnalyticsInsightsCache(
                student_id=student_id,
                insights_data=insights_data,
                behavioral_summary=report.behavioral_summary,
                generated_at=now,
                expires_at=expires_at,
                generation_count=1,
            )
            db.add(cache_entry)
            logger.info(f"Created insights cache for student: {student_id}")
        
        await db.commit()
    
    async def _generate_fresh_insights(
        self,
        student_id: str,
        db: AsyncSession,
    ) -> "AnalyticsReport":
        """
        Generate fresh LLM-powered insights for a student.
        
        Steps:
        1. Aggregate behavioral data from all sources
        2. Build context for LLM
        3. Generate insights via LLM
        4. Parse and structure response
        """
        # Step 1: Aggregate behavioral data
        behavioral_data = await self._aggregate_behavioral_data(student_id, db)
        
        # Step 2: Generate insights via LLM
        raw_insights = await self._call_llm_for_insights(behavioral_data)
        
        # Step 3: Structure the report
        report = AnalyticsReport(
            student_id=student_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            behavioral_summary=self._create_behavioral_summary(behavioral_data),
            insights=raw_insights.get("insights", []),
            predictions=raw_insights.get("predictions", {}),
            recommendations=raw_insights.get("recommendations", []),
            alerts=raw_insights.get("alerts", []),
        )
        
        return report
    
    async def generate_insights(
        self,
        student_id: str,
        db: AsyncSession,
    ) -> "AnalyticsReport":
        """Legacy method - generates fresh insights without caching."""
        return await self._generate_fresh_insights(student_id, db)
    
    async def _aggregate_behavioral_data(
        self,
        student_id: str,
        db: AsyncSession,
    ) -> BehavioralData:
        """Aggregate all behavioral data for a student."""
        
        # Get quiz attempts
        attempts_result = await db.execute(
            select(QuizAttempt).where(
                QuizAttempt.student_id == student_id,
                QuizAttempt.score.is_not(None),
            ).order_by(QuizAttempt.completed_at.desc())
        )
        attempts = attempts_result.scalars().all()
        
        # Get learning events
        events_result = await db.execute(
            select(LearningEvent).where(
                LearningEvent.student_id == student_id,
            ).order_by(LearningEvent.created_at.desc())
        )
        events = events_result.scalars().all()
        
        # Get chat sessions (tutor interactions) - just count them, don't load messages
        sessions_result = await db.execute(
            select(ChatSession).where(
                ChatSession.student_id == student_id,
            )
        )
        sessions = sessions_result.scalars().all()
        
        # Count messages separately to avoid lazy loading issues
        from sqlalchemy import func as sql_func
        from models.database import ChatMessage
        message_count_result = await db.execute(
            select(sql_func.count(ChatMessage.message_id)).where(
                ChatMessage.session_id.in_([s.session_id for s in sessions])
            )
        ) if sessions else None
        total_message_count = message_count_result.scalar() if message_count_result else 0
        
        # Get learning path
        path_result = await db.execute(
            select(LearningPath).where(
                LearningPath.student_id == student_id,
                LearningPath.status == "active",
            )
        )
        path = path_result.scalar_one_or_none()
        
        # Get generated resources consumed
        resources_result = await db.execute(
            select(GeneratedResource).where(
                GeneratedResource.student_id == student_id,
            )
        )
        resources = resources_result.scalars().all()
        
        # Calculate study patterns
        study_sessions = self._extract_study_sessions(attempts, events)
        preferred_hours = self._calculate_preferred_hours(study_sessions)
        study_days = self._calculate_study_days(study_sessions)
        
        # Calculate quiz metrics
        quiz_data = self._analyze_quiz_performance(attempts)
        
        # Calculate resource engagement
        resource_stats = self._analyze_resource_engagement(resources, events)
        
        # Calculate tutor stats
        tutor_stats = self._analyze_tutor_sessions(sessions, total_message_count)
        
        # Calculate progress metrics
        progress = self._calculate_progress_metrics(attempts, path)
        
        # Calculate velocity
        velocity = self._calculate_learning_velocity(attempts, path)
        
        return BehavioralData(
            student_id=student_id,
            study_sessions=study_sessions[:20],  # Last 20 sessions
            preferred_study_hours=preferred_hours,
            study_days_pattern=study_days,
            avg_session_duration=self._avg_session_duration(study_sessions),
            quiz_attempts=quiz_data["attempts"],
            avg_quiz_score=quiz_data["avg_score"],
            score_trend=quiz_data["trend"],
            weak_topics=quiz_data["weak_topics"],
            strong_topics=quiz_data["strong_topics"],
            resources_by_type=resource_stats["by_type"],
            total_resources_consumed=resource_stats["total"],
            preferred_resource_type=resource_stats["preferred"],
            tutor_sessions_count=tutor_stats["count"],
            avg_messages_per_session=tutor_stats["avg_messages"],
            common_question_topics=tutor_stats["topics"],
            path_completion_pct=progress["completion_pct"],
            current_streak=progress["current_streak"],
            longest_streak=progress["longest_streak"],
            days_since_last_activity=progress["days_inactive"],
            nodes_completed_last_7_days=velocity["last_7_days"],
            nodes_completed_last_30_days=velocity["last_30_days"],
            estimated_completion_days=velocity["estimated_days"],
        )
    
    def _extract_study_sessions(
        self,
        attempts: List[QuizAttempt],
        events: List[LearningEvent],
    ) -> List[Dict[str, Any]]:
        """Extract study sessions from quiz attempts and events."""
        sessions = []
        
        for attempt in attempts:
            if attempt.completed_at:
                sessions.append({
                    "date": attempt.completed_at.strftime("%Y-%m-%d"),
                    "start_time": attempt.completed_at.strftime("%H:%M"),
                    "hour": attempt.completed_at.hour,
                    "duration": (attempt.time_spent_seconds or 0) // 60,
                    "type": "quiz",
                    "topic": attempt.quiz_id,  # Would need to join for actual topic
                })
        
        for event in events:
            if event.created_at and event.event_type in ["resource_consumed", "resource_viewed"]:
                duration = event.event_data.get("duration_seconds", 0) // 60 if event.event_data else 0
                sessions.append({
                    "date": event.created_at.strftime("%Y-%m-%d"),
                    "start_time": event.created_at.strftime("%H:%M"),
                    "hour": event.created_at.hour,
                    "duration": duration,
                    "type": event.event_type,
                    "topic": event.event_data.get("topic", "unknown") if event.event_data else "unknown",
                })
        
        # Sort by date descending
        sessions.sort(key=lambda x: x["date"], reverse=True)
        return sessions
    
    def _calculate_preferred_hours(self, sessions: List[Dict]) -> List[int]:
        """Find the most common study hours."""
        hour_counts: Dict[int, int] = {}
        for s in sessions:
            hour = s.get("hour", 12)
            hour_counts[hour] = hour_counts.get(hour, 0) + 1
        
        # Return top 3 hours
        sorted_hours = sorted(hour_counts.items(), key=lambda x: x[1], reverse=True)
        return [h for h, _ in sorted_hours[:3]]
    
    def _calculate_study_days(self, sessions: List[Dict]) -> Dict[str, int]:
        """Count study sessions by day of week."""
        days = {"Mon": 0, "Tue": 0, "Wed": 0, "Thu": 0, "Fri": 0, "Sat": 0, "Sun": 0}
        day_names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        
        for s in sessions:
            try:
                date = datetime.strptime(s["date"], "%Y-%m-%d")
                day_name = day_names[date.weekday()]
                days[day_name] += 1
            except (ValueError, KeyError):
                pass
        
        return days
    
    def _avg_session_duration(self, sessions: List[Dict]) -> float:
        """Calculate average session duration in minutes."""
        durations = [s.get("duration", 0) for s in sessions if s.get("duration", 0) > 0]
        return round(sum(durations) / len(durations), 1) if durations else 0
    
    def _analyze_quiz_performance(self, attempts: List[QuizAttempt]) -> Dict[str, Any]:
        """Analyze quiz performance patterns."""
        if not attempts:
            return {
                "attempts": [],
                "avg_score": 0,
                "trend": "stable",
                "weak_topics": [],
                "strong_topics": [],
            }
        
        # Build attempts list
        attempt_data = []
        topic_scores: Dict[str, List[float]] = {}
        
        for a in attempts:
            score = a.score or 0
            topic = a.quiz_id  # Simplified - would join for actual topic
            
            attempt_data.append({
                "topic": topic,
                "score": round(score * 100, 1),
                "time_taken": a.time_spent_seconds or 0,
                "date": a.completed_at.strftime("%Y-%m-%d") if a.completed_at else "",
            })
            
            if topic not in topic_scores:
                topic_scores[topic] = []
            topic_scores[topic].append(score)
        
        # Calculate average
        avg_score = round(sum(a.score or 0 for a in attempts) / len(attempts) * 100, 1)
        
        # Calculate trend (compare first half vs second half)
        mid = len(attempts) // 2
        if mid > 0:
            first_half_avg = sum(a.score or 0 for a in attempts[mid:]) / (len(attempts) - mid)
            second_half_avg = sum(a.score or 0 for a in attempts[:mid]) / mid
            if second_half_avg > first_half_avg + 0.05:
                trend = "improving"
            elif second_half_avg < first_half_avg - 0.05:
                trend = "declining"
            else:
                trend = "stable"
        else:
            trend = "stable"
        
        # Find weak and strong topics
        topic_avgs = {t: sum(s) / len(s) for t, s in topic_scores.items()}
        sorted_topics = sorted(topic_avgs.items(), key=lambda x: x[1])
        
        weak_topics = [t for t, s in sorted_topics if s < 0.7][:3]
        strong_topics = [t for t, s in sorted_topics if s >= 0.8][:3]
        
        return {
            "attempts": attempt_data[:10],
            "avg_score": avg_score,
            "trend": trend,
            "weak_topics": weak_topics,
            "strong_topics": strong_topics,
        }
    
    def _analyze_resource_engagement(
        self,
        resources: List[GeneratedResource],
        events: List[LearningEvent],
    ) -> Dict[str, Any]:
        """Analyze resource consumption patterns."""
        by_type: Dict[str, int] = {}
        
        for r in resources:
            rtype = r.resource_type or "unknown"
            by_type[rtype] = by_type.get(rtype, 0) + 1
        
        # Also count from events
        for e in events:
            if e.event_type == "resource_consumed" and e.event_data:
                rtype = e.event_data.get("resource_type", "unknown")
                by_type[rtype] = by_type.get(rtype, 0) + 1
        
        total = sum(by_type.values())
        preferred = max(by_type.items(), key=lambda x: x[1])[0] if by_type else "none"
        
        return {
            "by_type": by_type,
            "total": total,
            "preferred": preferred,
        }
    
    def _analyze_tutor_sessions(self, sessions: List[ChatSession], total_message_count: int = 0) -> Dict[str, Any]:
        """Analyze tutor session patterns."""
        if not sessions:
            return {"count": 0, "avg_messages": 0, "topics": []}
        
        # Use pre-calculated message count to avoid lazy loading
        avg_messages = round(total_message_count / len(sessions), 1) if sessions else 0
        
        # Extract topics from session titles or current_node_id (these are already loaded)
        topics = []
        for s in sessions:
            if s.title and s.title != "New Chat":
                topics.append(s.title)
            elif s.current_node_id:
                topics.append(s.current_node_id)
        
        # Get most common topics
        topic_counts: Dict[str, int] = {}
        for t in topics:
            topic_counts[t] = topic_counts.get(t, 0) + 1
        
        common_topics = sorted(topic_counts.items(), key=lambda x: x[1], reverse=True)[:3]
        
        return {
            "count": len(sessions),
            "avg_messages": avg_messages,
            "topics": [t for t, _ in common_topics],
        }
    
    def _calculate_progress_metrics(
        self,
        attempts: List[QuizAttempt],
        path: Optional[LearningPath],
    ) -> Dict[str, Any]:
        """Calculate progress and streak metrics."""
        # Completion percentage
        completion_pct = 0
        if path and path.path_sequence:
            total_nodes = len(path.path_sequence)
            completed_nodes = len(attempts)  # Simplified
            completion_pct = round((completed_nodes / total_nodes) * 100, 1) if total_nodes > 0 else 0
        
        # Streak calculation
        if not attempts:
            return {
                "completion_pct": completion_pct,
                "current_streak": 0,
                "longest_streak": 0,
                "days_inactive": 999,
            }
        
        dates = set()
        for a in attempts:
            if a.completed_at:
                dates.add(a.completed_at.date())
        
        if not dates:
            return {
                "completion_pct": completion_pct,
                "current_streak": 0,
                "longest_streak": 0,
                "days_inactive": 999,
            }
        
        sorted_dates = sorted(dates, reverse=True)
        last_date = sorted_dates[0]
        today = datetime.now(timezone.utc).date()
        days_inactive = (today - last_date).days
        
        # Current streak
        current_streak = 0
        check_date = today
        while check_date in dates or (check_date == today and days_inactive <= 1):
            if check_date in dates:
                current_streak += 1
            check_date -= timedelta(days=1)
        
        # Longest streak
        longest_streak = 1
        current_longest = 1
        for i in range(1, len(sorted_dates)):
            if (sorted_dates[i - 1] - sorted_dates[i]).days == 1:
                current_longest += 1
                longest_streak = max(longest_streak, current_longest)
            else:
                current_longest = 1
        
        return {
            "completion_pct": completion_pct,
            "current_streak": current_streak,
            "longest_streak": longest_streak,
            "days_inactive": days_inactive,
        }
    
    def _make_aware(self, dt: datetime) -> datetime:
        """Ensure datetime is timezone-aware (UTC)."""
        if dt.tzinfo is None:
            return dt.replace(tzinfo=timezone.utc)
        return dt
    
    def _calculate_learning_velocity(
        self,
        attempts: List[QuizAttempt],
        path: Optional[LearningPath],
    ) -> Dict[str, Any]:
        """Calculate learning velocity and estimate completion."""
        now = datetime.now(timezone.utc)
        
        # Count completions in last 7 and 30 days
        last_7_days = sum(
            1 for a in attempts
            if a.completed_at and (now - self._make_aware(a.completed_at)).days <= 7
        )
        last_30_days = sum(
            1 for a in attempts
            if a.completed_at and (now - self._make_aware(a.completed_at)).days <= 30
        )
        
        # Estimate completion
        estimated_days = None
        if path and path.path_sequence and last_7_days > 0:
            remaining_nodes = len(path.path_sequence) - len(attempts)
            if remaining_nodes > 0:
                weekly_rate = last_7_days
                estimated_days = int((remaining_nodes / weekly_rate) * 7) if weekly_rate > 0 else None
        
        return {
            "last_7_days": last_7_days,
            "last_30_days": last_30_days,
            "estimated_days": estimated_days,
        }
    
    async def _call_llm_for_insights(self, data: BehavioralData) -> Dict[str, Any]:
        """Call Claude to generate insights from behavioral data."""
        
        prompt = f"""You are an AI learning analytics expert. Analyze this student's behavioral data and generate personalized insights.

## Student Behavioral Data

**Study Patterns:**
- Preferred study hours: {data.preferred_study_hours} (24h format)
- Study days pattern: {json.dumps(data.study_days_pattern)}
- Average session duration: {data.avg_session_duration} minutes
- Days since last activity: {data.days_since_last_activity}

**Quiz Performance:**
- Average score: {data.avg_quiz_score}%
- Score trend: {data.score_trend}
- Weak topics: {data.weak_topics}
- Strong topics: {data.strong_topics}
- Recent attempts: {json.dumps(data.quiz_attempts[:5])}

**Resource Engagement:**
- Resources by type: {json.dumps(data.resources_by_type)}
- Total consumed: {data.total_resources_consumed}
- Preferred type: {data.preferred_resource_type}

**Tutor Interactions:**
- Sessions: {data.tutor_sessions_count}
- Avg messages per session: {data.avg_messages_per_session}
- Common question topics: {data.common_question_topics}

**Progress:**
- Path completion: {data.path_completion_pct}%
- Current streak: {data.current_streak} days
- Longest streak: {data.longest_streak} days
- Nodes completed (7 days): {data.nodes_completed_last_7_days}
- Nodes completed (30 days): {data.nodes_completed_last_30_days}
- Estimated completion: {data.estimated_completion_days} days

## Instructions

Generate a JSON response with the following structure:

```json
{{
  "insights": [
    {{
      "category": "pattern|prediction|recommendation|alert",
      "emoji": "🌙",
      "title": "Short title",
      "description": "2-3 sentence insight in second person (you/your)",
      "confidence": 0.85,
      "priority": "high|medium|low"
    }}
  ],
  "predictions": {{
    "completion_forecast": "Description of when they'll complete",
    "at_risk": false,
    "at_risk_reason": null,
    "mastery_trajectory": "improving|stable|declining",
    "next_milestone_days": 5
  }},
  "recommendations": [
    {{
      "emoji": "💡",
      "title": "Action title",
      "description": "What to do and why",
      "priority": "high|medium|low"
    }}
  ],
  "alerts": [
    {{
      "emoji": "⚠️",
      "title": "Alert title",
      "description": "What needs attention",
      "severity": "warning|critical"
    }}
  ]
}}
```

Generate 3-5 insights, 2-3 recommendations, and only include alerts if there are genuine concerns (declining performance, long inactivity, etc.).

Be specific, actionable, and encouraging. Reference actual data points. Use emojis appropriately."""

        try:
            # Use the project's LLM client
            response = await self.llm.generate(
                messages=[
                    {"role": "system", "content": "You are an AI learning analytics expert. Always respond with valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                max_tokens=2000,
            )
            
            # Extract content from response
            content = ""
            if "choices" in response and len(response["choices"]) > 0:
                content = response["choices"][0].get("message", {}).get("content", "")
            
            if not content:
                logger.warning("Empty response from LLM")
                return self._fallback_insights(data)
            
            # Find JSON block
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                json_str = content[start:end]
                return json.loads(json_str)
            
            logger.warning("Could not extract JSON from LLM response")
            return self._fallback_insights(data)
            
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            return self._fallback_insights(data)
    
    def _fallback_insights(self, data: BehavioralData) -> Dict[str, Any]:
        """Generate basic insights without LLM if API fails."""
        insights = []
        recommendations = []
        alerts = []
        
        # Study pattern insight
        if data.preferred_study_hours:
            hour = data.preferred_study_hours[0]
            time_label = "night owl 🌙" if hour >= 21 else "early bird 🌅" if hour <= 8 else "afternoon learner ☀️"
            insights.append({
                "category": "pattern",
                "emoji": "🕐",
                "title": f"You're a {time_label}",
                "description": f"You study most often around {hour}:00. Your sessions average {data.avg_session_duration} minutes.",
                "confidence": 0.8,
                "priority": "medium",
            })
        
        # Performance insight
        if data.avg_quiz_score > 0:
            insights.append({
                "category": "pattern",
                "emoji": "📊",
                "title": f"Quiz Performance: {data.score_trend.title()}",
                "description": f"Your average score is {data.avg_quiz_score}%. Your performance is {data.score_trend}.",
                "confidence": 0.9,
                "priority": "medium",
            })
        
        # Weak topics recommendation
        if data.weak_topics:
            recommendations.append({
                "emoji": "🎯",
                "title": "Focus on Weak Areas",
                "description": f"Consider revisiting: {', '.join(data.weak_topics[:2])}. These topics need more practice.",
                "priority": "high",
            })
        
        # Inactivity alert
        if data.days_since_last_activity > 3:
            alerts.append({
                "emoji": "⚠️",
                "title": "Getting Rusty?",
                "description": f"It's been {data.days_since_last_activity} days since your last study session. Jump back in!",
                "severity": "warning",
            })
        
        return {
            "insights": insights,
            "predictions": {
                "completion_forecast": f"At your current pace, you'll complete in approximately {data.estimated_completion_days or 'unknown'} days.",
                "at_risk": data.days_since_last_activity > 7,
                "at_risk_reason": "Extended inactivity" if data.days_since_last_activity > 7 else None,
                "mastery_trajectory": data.score_trend,
                "next_milestone_days": data.estimated_completion_days,
            },
            "recommendations": recommendations,
            "alerts": alerts,
        }
    
    def _create_behavioral_summary(self, data: BehavioralData) -> Dict[str, Any]:
        """Create a summary of behavioral data for the report."""
        # Safely get busiest day
        busiest_day = None
        if data.study_days_pattern:
            non_zero_days = {k: v for k, v in data.study_days_pattern.items() if v > 0}
            if non_zero_days:
                busiest_day = max(non_zero_days.items(), key=lambda x: x[1])[0]
            else:
                busiest_day = "Mon"  # Default
        
        return {
            "study_pattern": {
                "preferred_hours": data.preferred_study_hours or [],
                "busiest_day": busiest_day,
                "avg_session_minutes": data.avg_session_duration or 0,
            },
            "performance": {
                "avg_score": data.avg_quiz_score,
                "trend": data.score_trend,
                "weak_topics": data.weak_topics,
                "strong_topics": data.strong_topics,
            },
            "engagement": {
                "preferred_resource": data.preferred_resource_type,
                "total_resources": data.total_resources_consumed,
                "tutor_sessions": data.tutor_sessions_count,
            },
            "progress": {
                "completion_pct": data.path_completion_pct,
                "current_streak": data.current_streak,
                "velocity_7d": data.nodes_completed_last_7_days,
            },
        }


# Singleton instance
_engine: Optional[AnalyticsEngine] = None


def get_analytics_engine() -> AnalyticsEngine:
    """Get or create the analytics engine singleton."""
    global _engine
    if _engine is None:
        _engine = AnalyticsEngine()
    return _engine
